#ifndef _CONSTS_H
#define _CONSTS_H

#define DISPLAY_WIDTH 600
#define DISPLAY_HEIGHT 600
#define FPS 60
#define SPACESHIP_LIVES 4
#define BLAST_INITIAL_TIMER 30
#define ACTIVATE_ASTEROID_INITIAL_TIMER 30
#define FONT "/home/dan/Documentos/Blasteroids/src/assets/GeostarFill.ttf"
#define WHITE_COLOR 255,255,255
#define SPACESHIP_COLOR WHITE_COLOR
#define ASTEROID_COLOR WHITE_COLOR
#define BLAST_COLOR WHITE_COLOR
#define BIG_ASTEROID_SCALE 1.0
#define MEDIUM_ASTEROID_SCALE 0.7
#define SMALL_ASTEROID_SCALE 0.5

#endif